name: ci

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        # go-version: 1.19
        go-version-file: go.mod
        # The builtin cache feature ensures that installing golangci-lint
        # is consistently fast.
        cache: true
        cache-dependency-path: go.sum

    - uses: nowsprinting/check-version-format-action@v3
      if: github.event_name != 'pull_request'
      id: version
      with:
        prefix: 'v'

    - name: Build app
      run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -a -installsuffix cgo -ldflags="-X 'main.version=${{ steps.version.outputs.full }}'" -o bin/webtty .
    
    - name: Generate MD5
      run: md5sum bin/webtty > bin/webtty.md5

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generate_release_notes: true
        files: |
          bin/webtty
          bin/webtty.md5
        prerelease: ${{ steps.version.outputs.prerelease }}
